import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { buildHeadlessE2E } from '../helpers/headless-e2e';
import { OpenAIProvider } from '../../src/providers/openai-provider';
import { adaptLegacyProvider } from '../../src/llm/legacy-adapter';
import type { LLMProvider } from '../../src/llm/contract';

const KEY = process.env.DEEPSEEK_KEY || '';

function realProvider(onAdvertised?: (tools: unknown) => void): LLMProvider {
  const raw = new OpenAIProvider({
    id: 'deepseek', apiKey: KEY, baseURL: 'https://api.deepseek.com', model: 'deepseek-v4-flash',
    maxTokens: 512,
  } as never);
  const adapted = adaptLegacyProvider(raw as never);
  return {
    ...adapted,
    generateWithTools: ((messages, onChunk, options) => {
      onAdvertised?.(options?.tools ?? []);
      return adapted.generateWithTools!(messages, onChunk, options);
    }) as LLMProvider['generateWithTools'],
  } as LLMProvider;
}

/**
 * L5.5 REAL end-to-end (DeepSeek + real tools + real fs vault) across several
 * realistic workflows. Network required. Asserts on the logged tool flow so a
 * wrong-args / wrong-result bug surfaces in the [E2E] log.
 */
describe('L5.5 real DeepSeek end-to-end scenarios', () => {
  it('reads a note and answers from its content (vault_read)', async () => {
    const advertised: unknown[] = [];
    const h = await buildHeadlessE2E(realProvider((t) => advertised.push(t)), {
      'notes/ideas.md': '# Ideas\nBuild a mentorship plugin for Obsidian.',
    });
    const res = await h.run('请用 vault_read 工具读取 notes/ideas.md，然后用中文告诉我这个文件讲的是什么。');
    const read = res.toolEnds.find((t) => t.name === 'vault_read');
    expect(read?.isError).toBe(false);
    expect((read?.result as { data?: { content?: string } }).data?.content).toContain('mentorship');
    expect(res.assistantText).toMatch(/mentorship|plugin|插件|思路/i);
    expect(advertised.length).toBeGreaterThan(0); // tools were actually advertised
  }, 60000);

  it('creates a new note and persists it to disk (vault_write)', async () => {
    const h = await buildHeadlessE2E(realProvider(), {
      'readme.md': 'existing',
    });
    const res = await h.run('请用 vault_write 工具创建一个新文件 notes/out.md，内容为 "Generated by Mentat"。');
    const write = res.toolEnds.find((t) => t.name === 'vault_write');
    expect(write?.isError).toBe(false);
    const outPath = join(h.root, 'notes/out.md');
    expect(existsSync(outPath)).toBe(true);
    expect(readFileSync(outPath, 'utf-8')).toContain('Generated by Mentat');
  }, 60000);

  it('finds a file by full-text search (vault_search)', async () => {
    const h = await buildHeadlessE2E(realProvider(), {
      'a.md': 'nothing special',
      'notes/plugin.md': 'Mentat is an AI plugin for Obsidian.',
    });
    const res = await h.run('请用 vault_search 工具搜索哪个文件包含 "plugin"，然后告诉我文件路径。');
    const search = res.toolEnds.find((t) => t.name === 'vault_search');
    expect(search?.isError).toBe(false);
    const results = ((search?.result as { data?: { path: string }[] }).data ?? []).map((r) => r.path);
    expect(results).toContain('notes/plugin.md');
    expect(res.assistantText).toMatch(/plugin/i);
  }, 60000);

  it('lists then reads a file in a multi-step turn (vault_list → vault_read)', async () => {
    const h = await buildHeadlessE2E(realProvider(), {
      'todo.md': 'Ship the feature',
      'notes/hello.md': 'Hello there',
    });
    const res = await h.run('请先用 vault_list 列出所有 markdown 文件，然后用 vault_read 读取 notes/hello.md 的内容。');
    const called = res.toolCalls.map((c) => c.name);
    expect(called).toContain('vault_list');
    expect(called).toContain('vault_read');
    const read = res.toolEnds.find((t) => t.name === 'vault_read');
    expect((read?.result as { data?: { content?: string } }).data?.content).toContain('Hello there');
  }, 60000);
});

describe('L5.5 real scenarios — multi-step (manual log audit)', () => {
  it('compares two notes and reflects BOTH contents in the answer', async () => {
    const h = await buildHeadlessE2E(realProvider(), {
      'notes/a.md': '# A\nThis note is about CATS.',
      'notes/b.md': '# B\nThis note is about DOGS.',
    });
    const res = await h.run('请读取 notes/a.md 和 notes/b.md，然后告诉我这两篇笔记各自的主题，并说明它们的区别。');
    const reads = res.toolCalls.filter((c) => c.name === 'vault_read');
    // The model should read BOTH files.
    console.log('[AUDIT] vault_read count =', reads.length, 'paths =', JSON.stringify(reads.map((r) => r.args)));
    console.log('[AUDIT] assistant =', res.assistantText);
    expect(reads.length).toBeGreaterThanOrEqual(2);
    expect(res.assistantText).toMatch(/CATS/i);
    expect(res.assistantText).toMatch(/DOGS/i);
  }, 60000);

  it('search then read the matched file (cross-tool)', async () => {
    const h = await buildHeadlessE2E(realProvider(), {
      'notes/plugin.md': 'Mentat is an AI plugin for Obsidian vaults.',
      'notes/other.md': 'nothing relevant here',
    });
    const res = await h.run('请用 vault_search 搜索包含 "plugin" 的文件，然后用 vault_read 读取它的第一句内容告诉我。');
    const names = res.toolCalls.map((c) => c.name);
    console.log('[AUDIT] tools called =', JSON.stringify(names));
    console.log('[AUDIT] assistant =', res.assistantText);
    expect(names).toContain('vault_search');
    expect(names).toContain('vault_read');
    expect(res.assistantText).toMatch(/plugin|AI/i);
  }, 60000);

  it('copies a note (read then write) and persists the copy', async () => {
    const h = await buildHeadlessE2E(realProvider(), {
      'notes/src.md': '# Source\noriginal content here',
    });
    const res = await h.run('请读取 notes/src.md 的内容，然后用 vault_write 把它原样写入 notes/copy.md。');
    const names = res.toolCalls.map((c) => c.name);
    console.log('[AUDIT] tools called =', JSON.stringify(names));
    console.log('[AUDIT] assistant =', res.assistantText);
    const { existsSync, readFileSync } = await import('fs');
    const { join } = await import('path');
    const copy = join(h.root, 'notes/copy.md');
    expect(existsSync(copy)).toBe(true);
    console.log('[AUDIT] copy.md content =', readFileSync(copy, 'utf-8'));
    expect(readFileSync(copy, 'utf-8')).toContain('original content here');
  }, 60000);
});

describe('L5.5 vague user prompts (no explicit tool instructions)', () => {
  it('answers directly from the vault when asked vaguely, without clarifying back', async () => {
    const h = await buildHeadlessE2E(realProvider(), {
      '笔记/人工智能.md': '# 人工智能\n机器学习、神经网络、深度学习是主要方向。',
      '笔记/金融.md': '# 金融\n风控、量化交易、贷前策略。',
    });
    // Deliberately vague — no tool names mentioned. The system prompt must
    // make the model explore then answer, not ask "what do you want".
    const res = await h.run('我的笔记都涉及哪些领域？');
    console.log('[AUDIT] vague-prompt tools =', JSON.stringify(res.toolCalls.map((c) => c.name)));
    console.log('[AUDIT] vague-prompt assistant =', res.assistantText);
    // A real answer: mentions domains from the note contents.
    expect(res.assistantText).toMatch(/人工智能|机器学习|金融|风控|量化/i);
  }, 60000);
});
